/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.min;

import core.HLoader;
import core.pasarela;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONObject;

/**
 *
 * @author wit
 */
public class adm_sucs extends javax.swing.JInternalFrame {

    /**
     * Creates new form adm_tipos_cuenta
     */
    public adm_sucs() {
        initComponents();
        cargarTabla();
    }

    public void limpiarTabla() {
        tabla_tipos_cuenta.setAutoCreateRowSorter(true);
        tabla_tipos_cuenta.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, "Cargando...", null, null}
                },
                new String[]{
                    "Datos", "Sucursal", "Ciudad", "Direccion"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tabla_tipos_cuenta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabla_tipos_cuenta);
        if (tabla_tipos_cuenta.getColumnModel().getColumnCount() > 0) {
            tabla_tipos_cuenta.getColumnModel().getColumn(0).setMinWidth(1);
            tabla_tipos_cuenta.getColumnModel().getColumn(0).setPreferredWidth(1);
            tabla_tipos_cuenta.getColumnModel().getColumn(0).setMaxWidth(1);
            tabla_tipos_cuenta.getColumnModel().getColumn(1).setMinWidth(180);
            tabla_tipos_cuenta.getColumnModel().getColumn(1).setPreferredWidth(180);
            tabla_tipos_cuenta.getColumnModel().getColumn(1).setMaxWidth(180);
        }

    }

    public void cargarTabla() {
        limpiarTabla();
        txt_nom_mov.setText("");
        txt_val_loc.setText("");
        txt_val_rem.setText("");
        DefaultTableModel MTabla = (DefaultTableModel) tabla_tipos_cuenta.getModel();
        HLoader LOAD_TB = new HLoader(MTabla, "");
        LOAD_TB.tabla3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_tipos_cuenta = new javax.swing.JTable();
        txt_nom_mov = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_val_loc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_val_rem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Sucursales");

        tabla_tipos_cuenta.setAutoCreateRowSorter(true);
        tabla_tipos_cuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Cargando...", null, null}
            },
            new String [] {
                "Datos", "Sucursal", "Ciudad", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_tipos_cuenta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_tipos_cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_tipos_cuentaMouseClicked(evt);
            }
        });
        tabla_tipos_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_tipos_cuentaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_tipos_cuenta);

        txt_nom_mov.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nom_mov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nom_movActionPerformed(evt);
            }
        });

        jLabel1.setText("Ciudad");

        jLabel2.setText("Direccion");

        jScrollPane2.setViewportView(resumen);

        jToggleButton1.setText("Nueva");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Guardar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nom_mov, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(txt_val_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_val_rem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_nom_mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_val_loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_val_rem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_tipos_cuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_tipos_cuentaMouseClicked
        // TODO add your handling code here:
        cargarForm();
    }//GEN-LAST:event_tabla_tipos_cuentaMouseClicked

    private void tabla_tipos_cuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_tipos_cuentaKeyReleased
        // TODO add your handling code here:
        cargarForm();
    }//GEN-LAST:event_tabla_tipos_cuentaKeyReleased

    private void txt_nom_movActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nom_movActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nom_movActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        int UID = tabla_tipos_cuenta.getSelectedRow();
        if (UID >= 0) {
            UID = Integer.parseInt(tabla_tipos_cuenta.getValueAt(UID, 0).toString());
        } else {
            UID = -1;
        }
        JSONObject vector = new JSONObject();
        vector.put("API", "setTSucursal");
        vector.put("id", UID);
        vector.put("nom", txt_nom_mov.getText());
        vector.put("ciud", txt_val_loc.getText());
        vector.put("dir", txt_val_rem.getText());
        resumen.setText(pasarela.call(vector));
        cargarTabla();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        txt_nom_mov.setText("");
        txt_val_loc.setText("");
        txt_val_rem.setText("");
        txt_nom_mov.requestFocus();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void cargarForm() {
        int UID = tabla_tipos_cuenta.getSelectedRow();
        if (UID >= 0) {
            txt_nom_mov.setText(tabla_tipos_cuenta.getValueAt(UID, 1).toString());
            txt_val_loc.setText(tabla_tipos_cuenta.getValueAt(UID, 2).toString());
            txt_val_rem.setText(tabla_tipos_cuenta.getValueAt(UID, 3).toString());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextPane resumen;
    public static javax.swing.JTable tabla_tipos_cuenta;
    private javax.swing.JTextField txt_nom_mov;
    private javax.swing.JTextField txt_val_loc;
    private javax.swing.JTextField txt_val_rem;
    // End of variables declaration//GEN-END:variables
}
