/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.min;

import core.HLoader;
import core.pasarela;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONObject;

/**
 *
 * @author wit
 */
public class adm_tipos_cuenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form adm_tipos_cuenta
     */
    public adm_tipos_cuenta() {
        initComponents();
        cargarTabla();
    }

    public void limpiarTabla() {
        tabla_tipos_cuenta.setAutoCreateRowSorter(true);
        tabla_tipos_cuenta.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, "Cargando..."}
                },
                new String[]{
                    "Datos", "Tipo Cuenta"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tabla_tipos_cuenta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jScrollPane1.setViewportView(tabla_tipos_cuenta);
        if (tabla_tipos_cuenta.getColumnModel().getColumnCount() > 0) {
            tabla_tipos_cuenta.getColumnModel().getColumn(0).setMinWidth(1);
            tabla_tipos_cuenta.getColumnModel().getColumn(0).setPreferredWidth(1);
            tabla_tipos_cuenta.getColumnModel().getColumn(0).setMaxWidth(1);
        }
    }

    public void cargarTabla() {
        limpiarTabla();
        txt_val_rem.setText("");
        DefaultTableModel MTabla = (DefaultTableModel) tabla_tipos_cuenta.getModel();
        HLoader LOAD_TB = new HLoader(MTabla, "");
        LOAD_TB.tabla4();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_tipos_cuenta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_val_rem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Tipos de Cuenta");

        tabla_tipos_cuenta.setAutoCreateRowSorter(true);
        tabla_tipos_cuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Cargando..."}
            },
            new String [] {
                "Datos", "Tipo Cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_tipos_cuenta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_tipos_cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_tipos_cuentaMouseClicked(evt);
            }
        });
        tabla_tipos_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_tipos_cuentaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_tipos_cuenta);
        if (tabla_tipos_cuenta.getColumnModel().getColumnCount() > 0) {
            tabla_tipos_cuenta.getColumnModel().getColumn(0).setMinWidth(1);
            tabla_tipos_cuenta.getColumnModel().getColumn(0).setPreferredWidth(1);
            tabla_tipos_cuenta.getColumnModel().getColumn(0).setMaxWidth(1);
        }

        jLabel2.setText("Nombre Tipo Cuenta");

        jScrollPane2.setViewportView(resumen);

        jToggleButton1.setText("Nueva");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Guardar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_val_rem)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_val_rem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_tipos_cuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_tipos_cuentaMouseClicked
        // TODO add your handling code here:
        cargarForm();
    }//GEN-LAST:event_tabla_tipos_cuentaMouseClicked

    private void tabla_tipos_cuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_tipos_cuentaKeyReleased
        // TODO add your handling code here:
        cargarForm();
    }//GEN-LAST:event_tabla_tipos_cuentaKeyReleased

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        int UID = tabla_tipos_cuenta.getSelectedRow();
        if (UID >= 0) {
            UID = Integer.parseInt(tabla_tipos_cuenta.getValueAt(UID, 0).toString());
        } else {
            UID = -1;
        }
        JSONObject vector = new JSONObject();
        vector.put("API", "setTTPCuenta");
        vector.put("id", UID);
        vector.put("tipo", txt_val_rem.getText());
        resumen.setText(pasarela.call(vector));
        cargarTabla();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        txt_val_rem.setText("");
        txt_val_rem.requestFocus();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void cargarForm() {
        int UID = tabla_tipos_cuenta.getSelectedRow();
        if (UID >= 0) {
            txt_val_rem.setText(tabla_tipos_cuenta.getValueAt(UID, 1).toString());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextPane resumen;
    public static javax.swing.JTable tabla_tipos_cuenta;
    private javax.swing.JTextField txt_val_rem;
    // End of variables declaration//GEN-END:variables
}
