/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import config.Globales;
import config.Storages;
import core.item_combo;
import core.json;
import core.pasarela;
import javax.swing.DefaultComboBoxModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author rosvel
 */
public class principal_cliente extends javax.swing.JFrame {

    DefaultComboBoxModel miComboAccion, miComboCuentas;

    /**
     * Creates new form principal_cliente
     */
    public principal_cliente() {
        Storages.infoTerminal();
        initComponents();
        this.setLocationRelativeTo(null);
        miComboCuentas = new DefaultComboBoxModel();
        miComboAccion = new DefaultComboBoxModel();
        jComboBox1.setModel(miComboCuentas);
        jComboBox2.setModel(miComboAccion);
        llenarComboAccion();
        llenarComboCuentas();
        nom_suc.setText(Globales.SUCURSAL_NOMBRE);
        ciu_suc.setText(Globales.SUCURSAL_CIUDAD);
        dir_suc.setText(Globales.SUCURSAL_DIR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumen_operacion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        ciu_suc = new javax.swing.JLabel();
        nom_suc = new javax.swing.JLabel();
        dir_suc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Cuentas");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Acción");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        jComboBox2.setEnabled(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Valor");

        jTextField1.setEnabled(false);

        jButton1.setText("Ejecutar Acción");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resumen_operacion.setEditable(false);
        resumen_operacion.setColumns(20);
        resumen_operacion.setRows(5);
        resumen_operacion.setWrapStyleWord(true);
        resumen_operacion.setEnabled(false);
        jScrollPane1.setViewportView(resumen_operacion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ATM & ATH");

        ciu_suc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ciu_suc.setText("{{ciu_suc}}");

        nom_suc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nom_suc.setText("{{nom_suc}}");

        dir_suc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dir_suc.setText("{{dir_suc}}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addGap(92, 92, 92))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ciu_suc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nom_suc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dir_suc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom_suc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ciu_suc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dir_suc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        //item_combo item = (item_combo) miComboAccion.getSelectedItem();
        //System.out.println(item.getId()+" => "+item.getLabel());
        if (jComboBox2.getSelectedIndex() != 0) {
            item_combo item = (item_combo) miComboAccion.getSelectedItem();
            if (item.getId() != 0) {
                jTextField1.setEnabled(true);
                jButton1.setEnabled(true);
                resumen_operacion.setEnabled(true);
            }
        } else {
            jTextField1.setText("");
            resumen_operacion.setText("");
            jTextField1.setEnabled(false);
            jButton1.setEnabled(false);
            resumen_operacion.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() != 0) {
            jComboBox2.setEnabled(true);
            jComboBox2.requestFocus();
        } else {
            jComboBox2.setSelectedIndex(0);
            jComboBox2.setEnabled(false);
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        item_combo itemCuenta = (item_combo) miComboCuentas.getSelectedItem();
        item_combo itemAccion = (item_combo) miComboAccion.getSelectedItem();
        JSONObject Preparar = new JSONObject();
        Preparar.put("API", "setMovimiento");
        Preparar.put("cuenta_id", itemCuenta.getId());
        Preparar.put("tipo_movimiento_id", itemAccion.getId());
        Preparar.put("sucursal_id", Globales.TERMINAL_ID);
        Preparar.put("valor_movimiento", (jTextField1.getText().equals("") ? 0 : jTextField1.getText()));
        String rta = pasarela.call(Preparar);
        JSONObject vector = json.decode(rta);
        String print = "Monto del movimiento: " + jTextField1.getText() + "\n"
                + "Costo del movimiento: " + vector.get("costo_movimiento") + "\n"
                + "Saldo anterior: " + vector.get("saldo_anterior") + "\n"
                + "Saldo actual: " + vector.get("saldo_actual");
        resumen_operacion.setText(print);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_cliente().setVisible(true);
            }
        });
    }

    private void llenarComboAccion() {
        JSONObject Preparar = new JSONObject();
        Preparar.put("API", "getTipoMovimiento");
        String rta = pasarela.call(Preparar);
        Preparar.clear();
        Preparar = json.decode(rta);
        JSONArray arreglo = (JSONArray) Preparar.get("movimientos");
        miComboAccion.removeAllElements();
        miComboAccion.addElement(new item_combo(0, "Seleccione..."));
        for (int i = 0; i < arreglo.size(); i++) {
            JSONObject elemento = json.decode(arreglo.get(i).toString());
            miComboAccion.addElement(new item_combo(Integer.parseInt(elemento.get("id").toString()), elemento.get("label").toString()));
        }
    }

    private void llenarComboCuentas() {
        JSONObject Preparar = new JSONObject();
        Preparar.put("API", "getCuentasUsuario");
        Preparar.put("persona_id", Globales.PER_ID);
        String rta = pasarela.call(Preparar);
        Preparar.clear();
        Preparar = json.decode(rta);
        JSONArray arreglo = (JSONArray) Preparar.get("cuentas");
        miComboCuentas.removeAllElements();
        miComboCuentas.addElement(new item_combo(0, "Seleccione..."));
        for (int i = 0; i < arreglo.size(); i++) {
            JSONObject elemento = json.decode(arreglo.get(i).toString());
            miComboCuentas.addElement(new item_combo(Integer.parseInt(elemento.get("id").toString()), elemento.get("label").toString()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel ciu_suc;
    public static javax.swing.JLabel dir_suc;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel nom_suc;
    private javax.swing.JTextArea resumen_operacion;
    // End of variables declaration//GEN-END:variables
}
